#pragma once

//순서주의!!
//오브젝트들 모음
enum OBJECT_DEFINE
{
	OBJECT_BACKGROUND,
	OBJECT_WAYPOINT, //웨이포인트
	
	OBJECT_MONSTER1,
	OBJECT_MONSTER2,
	OBJECT_BOSS,
	OBJECT_PLAYER,
	/////////////////////////////////////
	OBJECT_ISAAC, //갓비오
	OBJECT_YUUSHA, //용사
	OBJECT_SONIC, //소닉 
	OBJECT_SETRECT,
	OBJECT_SHOPNPC, //장비샵
	OBJECT_PSHOPNPC, //포션샵
	
	OBJECT_PANEL, //피통 마나통 보이는 패널
	OBJECT_INFO, //캐릭인포
	OBJECT_INVEN, //인벤토리
	OBJECT_QUEST, //퀘스트인포
	OBJECT_QUESTMGR, //퀘스트 메니저용

};

//enum OBJECT_STAGE //안씀
//{
//	OBJECT_BACKGROUND,
//	OBJECT_PLAYER,
//	OBJECT_MONSTER1,
//	OBJECT_STAGE_MONSTER2,
//	OBJECT_STAGE_BOSS,
//	OBJECT_STAGE_SETRECT,
//};
//enum OBJECT_ACT2 //안씀
//{
//	OBJECT_BACKGROUND,
//	OBJECT_ACT2_PLAYER,
//	OBJECT_ACT2_MONSTER1,
//	OBJECT_ACT2_MONSTER2,
//	OBJECT_ACT2_BOSS,
//	OBJECT_ACT2_SETRECT,
//};

enum OBJECT_STATEID_BACKGROUND
{
	OBJECT_STATEID_BACKGROUND_TILE,
	OBJECT_STATEID_BACKGROUND_OBJECT,
};

enum OBJECT_STATEID_ACT2BACK
{
	OBJECT_STATEID_ACT2BACK_TILE,
	OBJECT_STATEID_ACT2BACK_OBJECT,
};

enum OBJECT_STATEID_PLAYER
{
	///방향은 캐릭터 얼굴이 향하는곳 기준으로 시계방향(1이 정면을 보고있음)
	OBJECT_STATEID_PLAYER_STAND1, // 292.5~247.5 캐릭터 얼굴이 정면을 향하는 위치
	OBJECT_STATEID_PLAYER_STAND2, // 247.5~202.5
	OBJECT_STATEID_PLAYER_STAND3, // 202.5~157.5
	OBJECT_STATEID_PLAYER_STAND4, // 157.5~112.5
	OBJECT_STATEID_PLAYER_STAND5, // 112.5~67.5 캐릭터의 등짝이 보이는 위치
	OBJECT_STATEID_PLAYER_STAND6, // 67.5~22.5
	OBJECT_STATEID_PLAYER_STAND7, // 22.5~337.5
	OBJECT_STATEID_PLAYER_STAND8, // 337.5~292.5
	OBJECT_STATEID_PLAYER_STAND9,
	OBJECT_STATEID_PLAYER_STAND10,
	OBJECT_STATEID_PLAYER_STAND11,
	OBJECT_STATEID_PLAYER_STAND12,
	OBJECT_STATEID_PLAYER_STAND13,
	OBJECT_STATEID_PLAYER_STAND14,
	OBJECT_STATEID_PLAYER_STAND15,
	OBJECT_STATEID_PLAYER_STAND16,
	//뛰기
	OBJECT_STATEID_PLAYER_RUN1,	
	OBJECT_STATEID_PLAYER_RUN2,	
	OBJECT_STATEID_PLAYER_RUN3,	
	OBJECT_STATEID_PLAYER_RUN4,	
	OBJECT_STATEID_PLAYER_RUN5,	
	OBJECT_STATEID_PLAYER_RUN6,	
	OBJECT_STATEID_PLAYER_RUN7,	
	OBJECT_STATEID_PLAYER_RUN8,
	OBJECT_STATEID_PLAYER_RUN9,
	OBJECT_STATEID_PLAYER_RUN10,
	OBJECT_STATEID_PLAYER_RUN11,
	OBJECT_STATEID_PLAYER_RUN12,
	OBJECT_STATEID_PLAYER_RUN13,
	OBJECT_STATEID_PLAYER_RUN14,
	OBJECT_STATEID_PLAYER_RUN15,
	OBJECT_STATEID_PLAYER_RUN16,
	//공격
	OBJECT_STATEID_PLAYER_ATTACK1,	
	OBJECT_STATEID_PLAYER_ATTACK2,	
	OBJECT_STATEID_PLAYER_ATTACK3,	
	OBJECT_STATEID_PLAYER_ATTACK4,	
	OBJECT_STATEID_PLAYER_ATTACK5,	
	OBJECT_STATEID_PLAYER_ATTACK6,	
	OBJECT_STATEID_PLAYER_ATTACK7,	
	OBJECT_STATEID_PLAYER_ATTACK8,
	OBJECT_STATEID_PLAYER_ATTACK9,
	OBJECT_STATEID_PLAYER_ATTACK10,
	OBJECT_STATEID_PLAYER_ATTACK11,
	OBJECT_STATEID_PLAYER_ATTACK12,
	OBJECT_STATEID_PLAYER_ATTACK13,
	OBJECT_STATEID_PLAYER_ATTACK14,
	OBJECT_STATEID_PLAYER_ATTACK15,
	OBJECT_STATEID_PLAYER_ATTACK16,
};

//액트1 : 카우
enum OBJECT_STATEID_MONSTER
{	
	///방향은 캐릭터 얼굴이 향하는곳 기준으로 시계방향(1이 정면을 보고있음)
	OBJECT_STATEID_MONSTER_STAND1, // 292.5~247.5 캐릭터 얼굴이 정면을 향하는 위치
	OBJECT_STATEID_MONSTER_STAND2, // 247.5~202.5
	OBJECT_STATEID_MONSTER_STAND3, // 202.5~157.5
	OBJECT_STATEID_MONSTER_STAND4, // 157.5~112.5
	OBJECT_STATEID_MONSTER_STAND5, // 112.5~67.5 캐릭터의 등짝이 보이는 위치
	OBJECT_STATEID_MONSTER_STAND6, // 67.5~22.5
	OBJECT_STATEID_MONSTER_STAND7, // 22.5~337.5
	OBJECT_STATEID_MONSTER_STAND8, // 337.5~292.5	
	//뛰기
	OBJECT_STATEID_MONSTER_RUN1,	
	OBJECT_STATEID_MONSTER_RUN2,	
	OBJECT_STATEID_MONSTER_RUN3,	
	OBJECT_STATEID_MONSTER_RUN4,	
	OBJECT_STATEID_MONSTER_RUN5,	
	OBJECT_STATEID_MONSTER_RUN6,	
	OBJECT_STATEID_MONSTER_RUN7,	
	OBJECT_STATEID_MONSTER_RUN8,
	//공격
	OBJECT_STATEID_MONSTER_ATTACK1,	
	OBJECT_STATEID_MONSTER_ATTACK2,	
	OBJECT_STATEID_MONSTER_ATTACK3,	
	OBJECT_STATEID_MONSTER_ATTACK4,	
	OBJECT_STATEID_MONSTER_ATTACK5,	
	OBJECT_STATEID_MONSTER_ATTACK6,	
	OBJECT_STATEID_MONSTER_ATTACK7,	
	OBJECT_STATEID_MONSTER_ATTACK8,
	//얻어맞음
	OBJECT_STATEID_MONSTER_HIT1,	
	OBJECT_STATEID_MONSTER_HIT2,	
	OBJECT_STATEID_MONSTER_HIT3,	
	OBJECT_STATEID_MONSTER_HIT4,	
	OBJECT_STATEID_MONSTER_HIT5,	
	OBJECT_STATEID_MONSTER_HIT6,	
	OBJECT_STATEID_MONSTER_HIT7,	
	OBJECT_STATEID_MONSTER_HIT8,

	//몬스터 죽는중
	OBJECT_STATEID_MONSTER_DIE1,

	//몬스터 죽음
	OBJECT_STATEID_MONSTER_DIE2,
};

//액트1 : 펄른족장, 액트2 : 
enum OBJECT_STATEID_MONSTER2
{
	///방향은 캐릭터 얼굴이 향하는곳 기준으로 시계방향(1이 정면을 보고있음)
	OBJECT_STATEID_MONSTER2_STAND1, // 292.5~247.5 캐릭터 얼굴이 정면을 향하는 위치
	OBJECT_STATEID_MONSTER2_STAND2, // 247.5~202.5
	OBJECT_STATEID_MONSTER2_STAND3, // 202.5~157.5
	OBJECT_STATEID_MONSTER2_STAND4, // 157.5~112.5
	OBJECT_STATEID_MONSTER2_STAND5, // 112.5~67.5 캐릭터의 등짝이 보이는 위치
	OBJECT_STATEID_MONSTER2_STAND6, // 67.5~22.5
	OBJECT_STATEID_MONSTER2_STAND7, // 22.5~337.5
	OBJECT_STATEID_MONSTER2_STAND8, // 337.5~292.5	
	//뛰기
	OBJECT_STATEID_MONSTER2_RUN1,	
	OBJECT_STATEID_MONSTER2_RUN2,	
	OBJECT_STATEID_MONSTER2_RUN3,	
	OBJECT_STATEID_MONSTER2_RUN4,	
	OBJECT_STATEID_MONSTER2_RUN5,	
	OBJECT_STATEID_MONSTER2_RUN6,	
	OBJECT_STATEID_MONSTER2_RUN7,	
	OBJECT_STATEID_MONSTER2_RUN8,
	//공격
	OBJECT_STATEID_MONSTER2_ATTACK1,	
	OBJECT_STATEID_MONSTER2_ATTACK2,	
	OBJECT_STATEID_MONSTER2_ATTACK3,	
	OBJECT_STATEID_MONSTER2_ATTACK4,	
	OBJECT_STATEID_MONSTER2_ATTACK5,	
	OBJECT_STATEID_MONSTER2_ATTACK6,	
	OBJECT_STATEID_MONSTER2_ATTACK7,	
	OBJECT_STATEID_MONSTER2_ATTACK8,
	//얻어맞음
	OBJECT_STATEID_MONSTER2_HIT1,	
	OBJECT_STATEID_MONSTER2_HIT2,	
	OBJECT_STATEID_MONSTER2_HIT3,	
	OBJECT_STATEID_MONSTER2_HIT4,	
	OBJECT_STATEID_MONSTER2_HIT5,	
	OBJECT_STATEID_MONSTER2_HIT6,	
	OBJECT_STATEID_MONSTER2_HIT7,	
	OBJECT_STATEID_MONSTER2_HIT8,

	//몬스터 죽는중
	OBJECT_STATEID_MONSTER2_DIE1,

	//몬스터 죽음
	OBJECT_STATEID_MONSTER2_DIE2,
};

//보스
enum OBJECT_STATEID_BOSS
{
	///방향은 캐릭터 얼굴이 향하는곳 기준으로 시계방향(1이 정면을 보고있음)
	OBJECT_STATEID_BOSS_STAND1, // 292.5~247.5 캐릭터 얼굴이 정면을 향하는 위치
	OBJECT_STATEID_BOSS_STAND2, // 247.5~202.5
	OBJECT_STATEID_BOSS_STAND3, // 202.5~157.5
	OBJECT_STATEID_BOSS_STAND4, // 157.5~112.5
	OBJECT_STATEID_BOSS_STAND5, // 112.5~67.5 캐릭터의 등짝이 보이는 위치
	OBJECT_STATEID_BOSS_STAND6, // 67.5~22.5
	OBJECT_STATEID_BOSS_STAND7, // 22.5~337.5
	OBJECT_STATEID_BOSS_STAND8, // 337.5~292.5	
	//뛰기
	OBJECT_STATEID_BOSS_RUN1,	
	OBJECT_STATEID_BOSS_RUN2,	
	OBJECT_STATEID_BOSS_RUN3,	
	OBJECT_STATEID_BOSS_RUN4,	
	OBJECT_STATEID_BOSS_RUN5,	
	OBJECT_STATEID_BOSS_RUN6,	
	OBJECT_STATEID_BOSS_RUN7,	
	OBJECT_STATEID_BOSS_RUN8,
	//공격
	OBJECT_STATEID_BOSS_ATTACK1,	
	OBJECT_STATEID_BOSS_ATTACK2,	
	OBJECT_STATEID_BOSS_ATTACK3,	
	OBJECT_STATEID_BOSS_ATTACK4,	
	OBJECT_STATEID_BOSS_ATTACK5,	
	OBJECT_STATEID_BOSS_ATTACK6,	
	OBJECT_STATEID_BOSS_ATTACK7,	
	OBJECT_STATEID_BOSS_ATTACK8,
	//얻어맞음
	OBJECT_STATEID_BOSS_HIT1,	
	OBJECT_STATEID_BOSS_HIT2,	
	OBJECT_STATEID_BOSS_HIT3,	
	OBJECT_STATEID_BOSS_HIT4,	
	OBJECT_STATEID_BOSS_HIT5,	
	OBJECT_STATEID_BOSS_HIT6,	
	OBJECT_STATEID_BOSS_HIT7,	
	OBJECT_STATEID_BOSS_HIT8,

	//몬스터 죽는중
	OBJECT_STATEID_BOSS_DIE1,

	//몬스터 죽음
	OBJECT_STATEID_BOSS_DIE2,
};

enum OBJECT_STATEID_INFO
{
	OBJECT_STATEID_INTERFACE_STATUS,


	//OBJECT_STATEID_INTERFACE_MAINBUTTON,


	//OBJECT_STATEID_INTERFACE_SHOP,

	//OBJECT_STATEID_INTERFACE_WAY,
	//OBJECT_STATEID_INTERFACE_UPBUTTON, //스텟 올리는 버튼 
	//OBJECT_STATEID_INTERFACE_WAYBUTTON,  //웨이포인트 버튼
};
enum OBJECT_STATEID_PANEL
{
	OBJECT_STATEID_PANEL_PANEL,
	OBJECT_STATEID_PANEL_HP,
	OBJECT_STATEID_PANELE_MP,
};
enum OBJECT_STATEID_INVEN
{
	OBJECT_STATEID_INVEN_INVEN,
};
enum OBJECT_STATEID_QUESTMGR
{
	OBJECT_STATEID_QUESTMGR_ALERT, //~을 해오세요 같은 알람
	OBJECT_STATEID_QUESTMGR_ALRAM, // 오른쪽에 뜨는 퀘스트 가이드
	OBJECT_STATEID_QUESTMGR_ARROW, // 퀘스트 장소를 알려주는 화살표
	OBJECT_STATEID_QUESTMGR_PLAYERTALK, //플레이어가 하는말
};
enum OBJECT_STATEID_QUEST
{
	OBJECT_STATEID_QUEST_QUEST, //퀘스트창
	OBJECT_STATEID_QUEST_QUESTALERT, //퀘스트알림
};

enum OBJECT_STATEID_SHOPNPC //장비상점
{
	OBJECT_STATEID_SHOPNPC_SHOPNPC, //엔피시 본체
	OBJECT_STATEID_SHOPNPC_SHOPLIST, //상점 이미지
};

enum OBJECT_STATEID_PSHOPNPC //포션상점
{
	OBJECT_STATEID_PSHOPNPC_PSHOPNPC, //엔피시 본체
	OBJECT_STATEID_PSHOPNPC_PSHOPLIST, //상점 이미지
};

enum OBJECT_STATEID_ISAAC //아이작 퀘스트1
{
	OBJECT_STATEID_ISAAC_ISAAC, //아이작 본체
	OBJECT_STATEID_ISAAC_TALK, //아이작 대화창
	OBJECT_STATEID_ISAAC_GOD, //갓비오
	OBJECT_STATEID_ISSAC_GTALK, //갓비오 대화창
};

enum OBJECT_STATEID_YUUSHA //용사 퀘스트2
{
	OBJECT_STATEID_YUUSHA_YUUSHA, //용사
	OBJECT_STATEID_YUUSHA_TALK,
};

enum OBJECT_STATEID_SONIC
{
	OBJECT_STATEID_SONIC_NOMAL, //마을에 있는 소닉
	OBJECT_STATEID_SONIC_HELP,	 //잡혀있는 소닉
	OBJECT_STATEID_SONIC_TALK,	//소닉 대화
};
enum OBJECT_STATEID_WAYPOINT //웨이포인트
{
	OBJECT_STATEID_WAYPOINT_WAYPOINT, //웨이포인트 본체
	OBJECT_STATEID_WAYPOINT_MENU, //웨이포인트 메뉴
};

enum OBJECT_LOGO //메인 배경으로 노동중
{
	OBJECT_LOGO_PLAYER,
	OBJECT_LOGO_MONSTER,
};

enum QUEST_NOW
{
	QUEST_NOW_QUEST0, //프롤로그 주인공 독백
	QUEST_NOW_QUEST1,
	QUEST_NOW_QUEST2,
	QUEST_NOW_QUEST3,
	QUEST_NOW_QUEST4,
	QUEST_NOW_QUEST5,
	QUEST_NOW_QUEST6,
	QUEST_NOW_QUEST7,
	QUEST_NOW_QUEST8,
	QUEST_NOW_QUEST9,
};

enum STATEID
{
	STATEID_LOGO,
	STATEID_ACT1,
	STATEID_ACT2,
	STATEID_ACT3,
	STATEID_END,
};

enum RECT_ID
{
	RECT_ID_ATK,
	RECT_ID_OBJ,
	RECT_ID_CLICK,
};
enum TEXTYPE
{
	TEXTYPE_SINGLE,
	TEXTYPE_MULTI,
};